= Commerce Cloud B2C Data Connector Release Notes

October 2020

_Support Category: Select_

Anypoint Connector for Commerce Cloud B2C Data APIs provides Mule users with a quick and easy way to integrate with Salesforce Commerce Cloud B2C Data API endpoints.

== 1.0.0 
October 2020

This release of Commerce Cloud B2C Data Connector is compatible with Mule 4 but not Mule 3.

== Compatibility
Commerce Cloud B2C Data Connector is compatible with these software versions:

[%header%autowidth.spread]
|===
|Software |Version
|Anypoint Studio |7 and later
|Mule runtime engine |4.2.1 and later
|JDK |1.8.x
|===

== Features

Commerce Cloud B2C Data Connector provides access to Salesforce Commerce Cloud B2C Data APIs for the below workflows:

* Assignments
* Campaigns
* Catalogs
* Coupons
* Customers
* Gift Certificates
* Orders
* Products
* Promotions
* Source Code Groups

== Fixed in This Release
Not applicable: This is the first released version.

== See Also
* https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Anypoint Connectors Support Policy]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
 